server:
  port: 9010
spring:
  application:
    name: clothes
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://39.98.174.77:3306/recommand?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://39.98.174.77:8761/eureka
  instance:
    prefer-ip-address: true
env:
  dev1
