server:
  port: 9010
spring:
  application:
    name: clothes
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://39.98.174.77:3304/recommand?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  dev1
